Error:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
UnauthenticatedError:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
          example: 401
        message:
          type: string
          example: unauthenticated
UnauthorizedError:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
          example: 403
        message:
          type: string
          example: unauthorized
MissingParamsError:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: Employee is missing
DataOperationError:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
          example: 422
        message:
          type: string
          example: Request pic must belong to project
SendEmailError:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
          example: 600
        message:
          type: string
          example: Email can't be sent because of some invalid email informations
InvalidEmailToken:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
          example: 401
        message:
          type: string
          example: Verify token is invalid or has been expired
SuccessMessage:
  type: object
  properties:
    message:
      type: string
      example: Delete successfully
User:
  type: object
  properties:
    id:
      type: integer
      description: User ID
      example: 1
    name:
      type: string
      description: User's name
      example: Sang
    email:
      type: string
      description: User's email
      example: tungvu@gmail.com
    birthday:
      type: date
      description: User's birthday
      example: 1996-11-02
    avatar:
      type: string
      description: Path to avatar
      example: "/uploads/avatar.png"
UserToken:
  type: object
  properties:
    token:
      type: string
      description: user token use for api
      example: Bearer eyJhbGciOiJSUzI1NiJ9.eyJlbXBsb3llZV9pZCI6MTAsIn
    expired_at:
      type: datetime
      description: expired time of token
      example: 2018-10-10T10:14:54.337+07:00
    user_id:
      type: integer
      description: user id
      example: 10
