Error:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
UnauthenticatedError:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
          example: 401
        message:
          type: string
          example: unauthenticated
UnauthorizedError:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
          example: 403
        message:
          type: string
          example: unauthorized
MissingParamsError:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: Employee is missing
DataOperationError:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
          example: 422
        message:
          type: string
          example: Request pic must belong to project
SendEmailError:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
          example: 600
        message:
          type: string
          example: Email can't be sent because of some invalid email informations
InvalidEmailToken:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: integer
          example: 401
        message:
          type: string
          example: Verify token is invalid or has been expired
SuccessMessage:
  type: object
  properties:
    message:
      type: string
      example: Delete successfully
Employee:
  type: object
  properties:
    id:
      type: integer
      description: Employee ID
      example: 1
    organization_id:
      type: integer
      description: Organization ID of employee
      example: 12
    name:
      type: string
      description: Employee's name
      example: Sang
    employee_code:
      type: string
      description: Employee's code
      example: B1210464
    email:
      type: string
      description: Employee's email
      example: etha.ebert@framgia.com
    birthday:
      type: date
      description: Employee's birthday
      example: 1996-11-02
    phone:
      type: string
      description: Employee's number phone
      example: 0987654321
    avatar:
      type: string
      description: Path to avatar
      example: "/uploads/avatar.png"
Project:
  type: object
  properties:
    id:
      type: integer
      description: Project ID
      example: 1
    name:
      type: string
      description: Project's name
      example: Project 1
    description:
      type: string
      description: Project's description
      example: Some description
    starts_on:
      type: date
      description: Start time of project
      example: "2018-01-01"
    logo:
      type: string
      description: Path to logo
      example: "2018-02-01"
    product_owner:
      description: Project owner of project
      allOf:
        - $ref: '#/Employee'
Device:
  allOf:
    - $ref: '#/BaseDevice'
    - type: object
      properties:
        project:
          type: object
          description: Project of device
          properties:
            product_owner_id:
              type: integer
              description: Product owner ID
Effort:
  type: object
  properties:
    id:
      type: integer
      description: Effort ID
      example: 1
    effort:
      type: integer
      description: Effort number
      example: 100
    employee_level:
      allOf:
        - $ref: '#/EmployeeLevel'
EmployeeLevel:
  type: object
  properties:
    name:
      type: string
      description: Employee's name
      example: Nguyen Van Sang
    id:
      type: integer
      description: Employee ID
      example: 1
    skill:
      description: Skill of employee
      allOf:
        - $ref: '#/SkillLevel'
SkillLevel:
  type: object
  properties:
    id:
      type: integer
      description: Skill ID
      example: 1
    name:
      type: string
      description: Skill name
      example: Ruby
    logo:
      type: string
      description: Logo url
      example: http://localhost:3000/uploads/avatar.png
    level:
      type: object
      description: Level of skill
      allOf:
        - $ref: '#/Level'
Level:
  type: object
  properties:
    id:
      type: integer
      description: Level ID
      example: 1
    name:
      type: string
      description: Level name
      example: Senior
    rank:
      type: integer
      description: Rank number
      example: 100
    logo:
      type: string
      description: Logo url
      example: https://cdn3.iconfinder.com/data/icons/avatars-15/64/_Ninja-2-512.png
BaseOrganization:
  type: object
  properties:
    id:
      type: integer
      description: Organization ID
      example: 1
    name:
      type: string
      description: Organization name
      example: Division 1
    parent_id:
      type: integer
      description: Organization parent
      example: 1
    manager_id:
      type: integer
      description: Manager id
      example: 3
    level:
      type: string
      description: Level of organization
      example: division
    children:
      allOf:
        - $ref: '#/BaseOrganization'
ProjectEffort:
  type: object
  properties:
    id:
      type: integer
      description: Employee id
      example: 1
    name:
      type: string
      description: Employee name
      example: Sang
    skill:
      description: Employee skill
      allOf:
        - $ref: '#/SkillLevel'
SprintMember:
  type: object
  properties:
    id:
      type: integer
      description: Sprint ID
      example: 1
    name:
      type: string
      description: Sprint name
      example: Sprint 1
    starts_on:
      type: date
      description: Start date of sprint
      example: "2018-01-01"
    ends_on:
      type: date
      description: End date of sprint
      example: "2018-02-01"
    members:
      description: Efforts of sprint
      allOf:
        - $ref: '#/ProjectEffort'
    phase_id:
      type: integer
      description: Phase ID
      example: 1
Sprint:
  type: object
  properties:
    id:
      type: integer
      description: Sprint ID
      example: 1
    name:
      type: string
      description: Sprint name
      example: Sprint 1
    starts_on:
      type: date
      description: Start date of sprint
      example: "2018-01-01"
    ends_on:
      type: date
      description: End date of sprint
      example: "2018-02-01"
EmployeeToken:
  type: object
  properties:
    token:
      type: string
      description: employee token use for api
      example: Bearer eyJhbGciOiJSUzI1NiJ9.eyJlbXBsb3llZV9pZCI6MTAsIn
    expired_at:
      type: datetime
      description: expired time of token
      example: 2018-10-10T10:14:54.337+07:00
    role:
      type: string
      description: employee's role
      example: TEAM_LEADER
    user_id:
      type: integer
      description: employee id
      example: 10
    organization_id:
      type: integer
      description: organization id of employee
      example: 9
Requirement:
  type: object
  properties:
    level_id:
      type: integer
      description: Level id
      example: 1
    phase_id:
      type: integer
      description: Phase id
      example: 1
    skill_name:
      type: string
      description: Skill name
      example: Ruby
    skill_level:
      type: string
      description: Level of skill
      example: Junior
    quantity:
      type: integer
      description: Quantity needed
      example: 10
Phase:
  type: object
  properties:
    id:
      type: integer
      description: Phase id
      example: 1
    name:
      type: string
      description: Phase name
      example: Phase 1
    starts_on:
      type: date
      description: Start date of phase
      example: "2018-01-01"
    ends_on:
      type: date
      description: End date of phase
      example: "2018-02-01"
BaseProject:
  type: object
  properties:
    id:
      type: integer
      description: Project ID
      example: 1
    name:
      type: string
      description: Project's name
      example: Project 1
    description:
      type: string
      description: Project's description
      example: Some description about project
    starts_on:
      type: date
      description: Start time of project
      example: "2018-01-01"
    logo:
      type: string
      description: Path to logo
      example: https://cdn3.iconfinder.com/data/icons/avatars-15/64/_Ninja-2-512.png
    product_owner_id:
      type: integer
      description: Product owner id
      example: 1000
Request:
  type: object
  properties:
    id:
      type: integer
      description: Request's id
    status:
      type: string
      description: Request's status
    modified_at:
      description: Request's modified date
      type: datetime
    project:
      description: Request Project
      allOf:
        - $ref: '#/BaseProject'
    request_pic:
      description: Request's persion in charge
      allOf:
        - $ref: '#/Employee'
    requester:
      description: Requester
      allOf:
        - $ref: '#/Employee'
BaseDevice:
  type: object
  properties:
    id:
      type: integer
      description: Device id
    name:
      type: string
      description: Device's name
    serial_code:
      description: Device's serial code
      type: string
    device_type:
      type: integer
      description: Type of device
    pic:
      description: Persion in charge
      allOf:
        - $ref: '#/Employee'
DeviceDetail:
  allOf:
    - $ref: '#/BaseDevice'
    - type: object
      properties:
        project:
          type: object
          description: Project of device
          allOf:
            - $ref: '#/BaseProject'
        history:
          type: array
          description: All of request
          items:
            allOf:
              - $ref: '#/Request'
Profile:
  allOf:
    - $ref: '#/EmployeeDetail'
    - type: object
      properties:
        owned_projects:
          type: array
          description: Projects that current user is product owner
          items:
            allOf:
            - $ref: '#/BaseProject'
        owned_organizations:
          type: array
          description: Organization that current user is manager
          items:
            allOf:
            - $ref: '#/Organizations'
ChatworkStatus:
  type: object
  properties:
    chatwork_status:
      type: string
      description: Chatwork's status of employee
      example: "off"
Organizations:
  type: object
  properties:
    id:
      type: integer
      description: Organization ID
      example: 1
    name:
      type: string
      description: Organization name
      example: Division 1
    parent_id:
      type: integer
      description: Organization parent
      example: 1
    manager_id:
      type: integer
      description: Manager id
      example: 3
    level:
      type: string
      description: Level of organization
      example: division
    ancestry:
      type: integer
      description: Acestry of organization
      example: 2
Organization:
  type: object
  properties:
    manager_name:
      type: string
      description: Name of manager's organization
      example: Nguyen Van A
    employee_ids:
      type: array
      description: Array of employee's ID of organization
      example: [1,2,3]
    full_name:
      type: string
      description: Full name of Organization
      example: "Group 1/Section 3/Division1"
    logo:
      type: string
      description: Logo's URL of organization
      example: "images/logo.png"
EmployeeDetail:
  allOf:
    - $ref: '#/Employee'
    - type: object
      properties:
        skills:
          type: array
          description: Skills of current user
          items:
            allOf:
            - $ref: '#/SkillLevel'
        devices:
          type: array
          description: Devices that current user in charge
          items:
            allOf:
            - $ref: '#/BaseDevice'
        projects:
          type: array
          description: Projects of current user
          items:
            allOf:
            - $ref: '#/BaseProject'
        organization:
          type: object
          description: Organization of current user
          allOf:
            - $ref: '#/Organizations'
