---
openapi: 3.0.0
info:
  title: API
  version: v1

servers:
  - url: //localhost:3000/api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authorization: Bearer #{token}"
security:
  - bearerAuth: []
paths:
  /session:
    $ref: api/session.yml#/~1session
  /users:
    $ref: api/users.yml#/~1users
