version: 2
jobs:
  build:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/ruby:2.5.1
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
      - image: circleci/postgres:9.5.13
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: emres_test
    steps:
      - checkout
      - restore_cache:
          key: bundle-test-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle

      - save_cache:
          key: bundle-test-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: bundle exec rake db:create RAILS_ENV=test

      - run: bundle exec rake db:migrate RAILS_ENV=test

      - run: bundle exec rspec spec

      - run: bundle exec rubocop
