default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['EMRES_DATABASE_USERNAME'] %>
  password: <%= ENV['EMRES_DATABASE_PASSWORD'] %>
  host: <%= ENV['EMRES_DATABASE_HOSTNAME'] %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: group_analysis_dev

test:
  <<: *default
  database: group_analysis_test

staging:
  <<: *default
  database: group_analysis_staging

production:
  <<: *default
  database: d4no19clql8ogj
  username: vdylrgowmdfjni
  password: 9d18b336ecb3268e0200c33327e8965b12459fda2581135c0847797b64f5b837
