default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['EMRES_DATABASE_USERNAME'] %>
  password: <%= ENV['EMRES_DATABASE_PASSWORD'] %>
  host: <%= ENV['EMRES_DATABASE_HOSTNAME'] %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: emres_development

test:
  <<: *default
  database: emres_test

staging:
  <<: *default
  database: emres_staging

production:
  <<: *default
  database: emres_production
  username: emres
  password: <%= ENV['EMRES_DATABASE_PASSWORD'] %>
