default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: 12345678
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: emres_development

test:
  <<: *default
  database: emres_test
  # username: root
  # password: ""

production:
  <<: *default
  database: emres_production
  username: emres
  password: <%= ENV['EMRES_DATABASE_PASSWORD'] %>
