access_token_header: "Authorization"
access_token_value_prefix: "Bearer"

http_code:
  code_200: 200
  code_400: 400
  code_404: 404
  code_401: 401
  code_403: 403

error_formatter:
  error_code_key: "error_code"
  error_codes:
    data_operation: 600
    unauthorized: 601
    token_expired: 602
    record_not_found: 603
    validation_errors: 604
    wrong_email_password: 605
    unauthenticated: 606
    decode_error: 601
    verification_error: 601

  message_key: "message"
  http_code:
    data_operation: 422
    unauthorized: 401
    token_expired: 401
    record_not_found: 404
    validation_errors: 400
    wrong_email_password: 401
    unauthenticated: 401
    decode_error: 401
    verification_error: 401

validations:
  strings:
    max_length: 255
  email_regex: !ruby/regexp '/\b[A-Z0-9._%a-z\-]+@framgia\.com\z/'
  password_regex: !ruby/regexp '/^(?=.*\d)(?=.*[#$@!%&*?])[A-Za-z\d#$@!%&*?]{8,}$/'

employee_tokens:
  token:
    secure_length: 64
  refresh_token:
    secure_length: 64
  expires_in: <%= 30.days %>
  short_expires_in: <%= 1.days %>

members_backend_id: ["2273997", "3127986", "1385477", "728173", "2047101", "2161732"]
members_frontend_id: ["1803370", "2310110", "1385477", "728173", "2047101", "2161732"]
leader_backend_id: "2310316"
leader_frontend_id: "1509321"
