access_token_header: "Emres-Authorization"
access_token_value_prefix: "Bearer"

http_code:
  code_200: 200
  code_400: 400
  code_404: 404
  code_401: 401
  code_403: 403

error_formatter:
  message_key: "message"
  http_code:
    data_operation: 422
    unauthorized: 403
    not_authorized_error: 403
    token_expired: 401
    record_not_found: 404
    validation_errors: 400
    # TODO: wrong email, password should return 401
    wrong_email_password: 400
    wrong_current_password: 400
    unauthenticated: 401
    decode_error: 401
    verification_error: 401
    send_email_error: 400
    invalid_email_token: 401

validations:
  strings:
    max_length: 255
  email_regex: !ruby/regexp '/\b[A-Z0-9._%a-z\-]+@framgia\.com\z/'
  password_regex: !ruby/regexp '/^(?=.*\d)(?=.*[#$@!%&*?])[A-Za-z\d#$@!%&*?]{8,}$/'
  phone_regex: !ruby/regexp '/\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/'

employee_tokens:
  token:
    secure_length: 64
  refresh_token:
    secure_length: 64
  expires_in: <%= 30.days %>
  short_expires_in: <%= 1.days %>

members_backend_id: ["2998532", "2847146", "2273997", "3127986", "1385477", "728173", "2047101", "2161732", "2261546"]
members_frontend_id: ["1803370", "2310110", "1385477", "728173", "2047101", "2161732", "2261546"]
leader_backend_id: "2310316"
leader_frontend_id: "1509321"

paginate:
  per_page:
    effort: 10
    employee: 8
    project: 9
    requirement: 5
    skill: 6
    sprint: 5
    device: 15
    request: 10

template:
  device_assignment:
    id: "d-7f046195d53749768c47ed7e2bb51305"
